// Package frost implements the Flexible Round-Optimized Schnorr Threshold (FROST)
// signature scheme as specified in RFC 9591.
//
// FROST is a threshold signature scheme that allows a threshold number of participants
// to cooperatively generate a signature, providing improved distribution of trust and
// redundancy with respect to secret keys.
package frost

import (
	"runtime"

	"github.com/jeremyhahn/go-frost/pkg/frost/group"
)

// Identifier represents a unique participant identifier.
// It is represented as a NonZeroScalar in the protocol specification.
type Identifier uint32

// Serialize returns the byte representation of the identifier.
// Uses big-endian encoding for consistent serialization across platforms.
func (id Identifier) Serialize() []byte {
	return []byte{
		byte(id >> 24),
		byte(id >> 16),
		byte(id >> 8),
		byte(id),
	}
}

// DeserializeIdentifier decodes a byte slice into an Identifier.
// Expects big-endian 4-byte encoding.
//
// Errors:
//   - Returns error if data length is not 4
//   - Returns error if the resulting identifier is zero
func DeserializeIdentifier(data []byte) (Identifier, error) {
	if len(data) != 4 {
		return 0, NewParameterError("data", "must be exactly 4 bytes", ErrDeserializationFailed)
	}

	id := Identifier(data[0])<<24 |
		Identifier(data[1])<<16 |
		Identifier(data[2])<<8 |
		Identifier(data[3])

	if id == 0 {
		return 0, NewParameterError("identifier", "cannot be zero", ErrInvalidParticipant)
	}

	return id, nil
}

// IsValid returns true if the identifier is non-zero.
func (id Identifier) IsValid() bool {
	return id != 0
}

// SigningCommitments represents the commitments generated by a participant
// during round one of the signing protocol.
type SigningCommitments struct {
	// Identifier of the participant who generated these commitments
	Identifier Identifier

	// HidingNonceCommitment is the commitment to the hiding nonce
	HidingNonceCommitment group.Element

	// BindingNonceCommitment is the commitment to the binding nonce
	BindingNonceCommitment group.Element
}

// SigningNonces represents the secret nonces generated by a participant
// during round one of the signing protocol.
type SigningNonces struct {
	// HidingNonce is the secret hiding nonce
	HidingNonce group.Scalar

	// BindingNonce is the secret binding nonce
	BindingNonce group.Scalar

	// Commitments are the corresponding public commitments
	Commitments SigningCommitments
}

// Zeroize securely erases the secret nonces from memory.
//
// This method should be called immediately after the nonces have been used
// in RoundTwo to prevent them from remaining in memory longer than necessary.
// Per RFC 9591 Section 7.3, nonces must not be reused, and they should be
// cleared from memory after use to reduce the risk of memory disclosure attacks.
//
// The method uses runtime.KeepAlive() to prevent the garbage collector from
// collecting the nonces before they are properly zeroed.
//
// Security considerations:
// - This provides defense-in-depth against memory disclosure attacks
// - Nonce reuse would lead to complete secret key recovery
// - Even with proper nonce generation, limiting exposure time is critical
//
// Example usage:
//
//	nonces, commitments, err := participant.RoundOne()
//	if err != nil {
//	    return err
//	}
//	defer nonces.Zeroize()  // Ensure cleanup even on error
//
//	share, err := participant.RoundTwo(nonces, msg, commitmentList)
//	// nonces will be zeroized when function returns
func (n *SigningNonces) Zeroize() {
	// Prevent GC from collecting before we zero the memory
	runtime.KeepAlive(n.HidingNonce)
	runtime.KeepAlive(n.BindingNonce)

	if n.HidingNonce != nil {
		// Get the underlying bytes and zero them
		hidingBytes := n.HidingNonce.Bytes()
		for i := range hidingBytes {
			hidingBytes[i] = 0
		}

		// Replace with a zero scalar
		zeroScalar := n.HidingNonce.Sub(n.HidingNonce)
		n.HidingNonce = zeroScalar
	}

	if n.BindingNonce != nil {
		// Get the underlying bytes and zero them
		bindingBytes := n.BindingNonce.Bytes()
		for i := range bindingBytes {
			bindingBytes[i] = 0
		}

		// Replace with a zero scalar
		zeroScalar := n.BindingNonce.Sub(n.BindingNonce)
		n.BindingNonce = zeroScalar
	}

	// Keep references alive until after we've zeroed them
	runtime.KeepAlive(n.HidingNonce)
	runtime.KeepAlive(n.BindingNonce)
}

// SignatureShare represents a participant's signature share generated
// during round two of the signing protocol.
type SignatureShare struct {
	// Identifier of the participant who generated this share
	Identifier Identifier

	// SignatureShare is the participant's signature share value
	SignatureShare group.Scalar
}

// Signature represents a complete FROST threshold signature.
type Signature struct {
	// R is the group commitment point
	R group.Element

	// Z is the aggregated signature scalar
	Z group.Scalar
}

// PublicKeyShare represents a participant's public key share.
type PublicKeyShare struct {
	// Identifier of the participant
	Identifier Identifier

	// PublicKey is the participant's public key share
	PublicKey group.Element
}

// SecretKeyShare represents a participant's secret key share.
type SecretKeyShare struct {
	// Identifier of the participant
	Identifier Identifier

	// SecretShare is the participant's secret key share
	SecretShare group.Scalar
}

// Zeroize securely erases the secret share from memory.
//
// This method should be called when the secret share is no longer needed
// to reduce the risk of memory disclosure attacks.
func (s *SecretKeyShare) Zeroize() {
	runtime.KeepAlive(s.SecretShare)
	if s.SecretShare != nil {
		bytes := s.SecretShare.Bytes()
		for i := range bytes {
			bytes[i] = 0
		}
		s.SecretShare = s.SecretShare.Sub(s.SecretShare)
	}
	runtime.KeepAlive(s.SecretShare)
}

// VerificationShare represents a participant's verification share
// used for validating secret shares during key generation.
type VerificationShare struct {
	// Identifier of the participant
	Identifier Identifier

	// VerificationKey is the public verification key
	VerificationKey group.Element
}

// KeyPackage contains all the key material for a participant.
type KeyPackage struct {
	// Identifier of the participant
	Identifier Identifier

	// SecretShare is the participant's secret key share
	SecretShare group.Scalar

	// PublicKey is the group's public key
	GroupPublicKey group.Element

	// VerificationShares contains all participants' verification shares
	VerificationShares []VerificationShare

	// MinSigners is the minimum number of participants required to sign (threshold)
	MinSigners uint32

	// MaxSigners is the maximum number of participants in the group
	MaxSigners uint32
}

// Zeroize securely erases the secret share from the key package.
//
// This method should be called when the key package is no longer needed
// to reduce the risk of memory disclosure attacks. Note that this only
// clears the secret share; the public key and verification shares are
// not sensitive and are left intact.
func (kp *KeyPackage) Zeroize() {
	runtime.KeepAlive(kp.SecretShare)
	if kp.SecretShare != nil {
		bytes := kp.SecretShare.Bytes()
		for i := range bytes {
			bytes[i] = 0
		}
		kp.SecretShare = kp.SecretShare.Sub(kp.SecretShare)
	}
	runtime.KeepAlive(kp.SecretShare)
}

// BindingFactor represents the binding factor for a participant
// computed during the signing protocol.
type BindingFactor struct {
	// Identifier of the participant
	Identifier Identifier

	// BindingFactor is the computed binding factor value
	BindingFactor group.Scalar
}

// Polynomial represents a polynomial over Scalars used in secret sharing.
// Coefficients are stored with the constant term first.
type Polynomial struct {
	// Coefficients of the polynomial, with coefficient[0] being the constant term
	Coefficients []group.Scalar
}

// Zeroize securely erases all polynomial coefficients from memory.
//
// This method should be called after key generation or DKG is complete
// to prevent the secret polynomial coefficients from remaining in memory.
// The constant term (coefficient[0]) is particularly sensitive as it
// represents the secret being shared.
func (p *Polynomial) Zeroize() {
	for i, coeff := range p.Coefficients {
		runtime.KeepAlive(coeff)
		if coeff != nil {
			bytes := coeff.Bytes()
			for j := range bytes {
				bytes[j] = 0
			}
			p.Coefficients[i] = coeff.Sub(coeff)
		}
	}
	for _, coeff := range p.Coefficients {
		runtime.KeepAlive(coeff)
	}
}

// CommitmentList is a sorted list of participant commitments.
// This list MUST be sorted in ascending order by participant identifier.
type CommitmentList []SigningCommitments

// BindingFactorList is a list of binding factors for participants.
type BindingFactorList []BindingFactor

// Configuration holds the FROST protocol configuration.
type Configuration struct {
	// MinSigners is the minimum number of participants required to sign (threshold)
	MinSigners uint32

	// MaxSigners is the maximum number of participants in the group
	MaxSigners uint32

	// Group is the prime-order group implementation
	Group group.Group
}
